// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_vector_mult,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.873000,HLS_SYN_LAT=25,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=51,HLS_SYN_LUT=177,HLS_VERSION=2019_1}" *)

module matrix_vector_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_address0,
        mat_ce0,
        mat_q0,
        vec_address0,
        vec_ce0,
        vec_q0,
        result_address0,
        result_ce0,
        result_we0,
        result_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] mat_address0;
output   mat_ce0;
input  [31:0] mat_q0;
output  [1:0] vec_address0;
output   vec_ce0;
input  [31:0] vec_q0;
output  [1:0] result_address0;
output   result_ce0;
output   result_we0;
output  [31:0] result_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mat_ce0;
reg vec_ce0;
reg result_ce0;
reg result_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] i_fu_107_p2;
reg   [1:0] i_reg_186;
wire    ap_CS_fsm_state2;
wire   [4:0] sub_ln10_fu_134_p2;
reg   [4:0] sub_ln10_reg_191;
wire   [0:0] icmp_ln7_fu_101_p2;
reg   [1:0] result_addr_reg_196;
wire   [1:0] j_fu_146_p2;
reg   [1:0] j_reg_204;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln9_fu_140_p2;
wire   [31:0] add_ln10_fu_177_p2;
wire    ap_CS_fsm_state4;
reg   [1:0] i_0_reg_66;
reg   [31:0] result_load_reg_77;
reg   [1:0] j_0_reg_90;
wire   [63:0] zext_ln8_fu_113_p1;
wire  signed [63:0] sext_ln10_fu_166_p1;
wire   [63:0] zext_ln10_fu_152_p1;
wire   [3:0] tmp_fu_122_p3;
wire   [4:0] zext_ln10_2_fu_130_p1;
wire   [4:0] zext_ln10_1_fu_118_p1;
wire   [4:0] zext_ln10_3_fu_157_p1;
wire   [4:0] add_ln10_1_fu_161_p2;
wire  signed [31:0] mul_ln10_fu_171_p0;
wire  signed [31:0] mul_ln10_fu_171_p1;
wire   [31:0] mul_ln10_fu_171_p2;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_140_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_66 <= i_reg_186;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_66 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_0_reg_90 <= j_reg_204;
    end else if (((icmp_ln7_fu_101_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_90 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        result_load_reg_77 <= add_ln10_fu_177_p2;
    end else if (((icmp_ln7_fu_101_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        result_load_reg_77 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_186 <= i_fu_107_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_204 <= j_fu_146_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_fu_101_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        result_addr_reg_196 <= zext_ln8_fu_113_p1;
        sub_ln10_reg_191 <= sub_ln10_fu_134_p2;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_ce0 = 1'b1;
    end else begin
        mat_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        vec_ce0 = 1'b1;
    end else begin
        vec_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln7_fu_101_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln9_fu_140_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_161_p2 = (sub_ln10_reg_191 + zext_ln10_3_fu_157_p1);

assign add_ln10_fu_177_p2 = (mul_ln10_fu_171_p2 + result_load_reg_77);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign i_fu_107_p2 = (i_0_reg_66 + 2'd1);

assign icmp_ln7_fu_101_p2 = ((i_0_reg_66 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_140_p2 = ((j_0_reg_90 == 2'd3) ? 1'b1 : 1'b0);

assign j_fu_146_p2 = (j_0_reg_90 + 2'd1);

assign mat_address0 = sext_ln10_fu_166_p1;

assign mul_ln10_fu_171_p0 = vec_q0;

assign mul_ln10_fu_171_p1 = mat_q0;

assign mul_ln10_fu_171_p2 = ($signed(mul_ln10_fu_171_p0) * $signed(mul_ln10_fu_171_p1));

assign result_address0 = result_addr_reg_196;

assign result_d0 = result_load_reg_77;

assign sext_ln10_fu_166_p1 = $signed(add_ln10_1_fu_161_p2);

assign sub_ln10_fu_134_p2 = (zext_ln10_2_fu_130_p1 - zext_ln10_1_fu_118_p1);

assign tmp_fu_122_p3 = {{i_0_reg_66}, {2'd0}};

assign vec_address0 = zext_ln10_fu_152_p1;

assign zext_ln10_1_fu_118_p1 = i_0_reg_66;

assign zext_ln10_2_fu_130_p1 = tmp_fu_122_p3;

assign zext_ln10_3_fu_157_p1 = j_0_reg_90;

assign zext_ln10_fu_152_p1 = j_0_reg_90;

assign zext_ln8_fu_113_p1 = i_0_reg_66;

endmodule //matrix_vector_mult
